name: saifbechan.github.io CD

on:
  push:
    branches: [main]

jobs:
  worker:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Unit tests & Linters (Node ${{ matrix.node-version }})
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: |
          yarn
          yarn tsc
          yarn tsc:cypress
          yarn lint
          yarn style
          yarn test
          yarn build
          yarn export
        env:
          CI: true
          DEPLOY_TARGET: gh-pages
      - run: touch out/.nojekyll

      - name: Cypress end-to-end tests
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start:test
          wait-on: http://localhost:3030

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true

      - uses: actions/checkout@v2
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v7
        with:
          urls: |
            https://saifbechan.me
          uploadArtifacts: true
          temporaryPublicStorage: true
