name: saifbechan.github.io CI

on:
  pull_request:
    branches: [main]

jobs:
  worker:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Unit tests & Linters (Node ${{ matrix.node-version }})
        uses: actions/setup-node@v2
        with:
          node-version: 15
      - run: |
          yarn
          yarn tsc
          yarn tsc:cypress
          yarn lint
          yarn style
          yarn test
          yarn build
          yarn export
        env:
          CI: true

      - name: Cypress end-to-end tests
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start:test
          wait-on: http://localhost:3030
